In [11]:
import pandas as pd

alunosDIC = {'Nome': ['Joao', 'Maria', 'Eduardo', 'Felipe'],
          'Nota': [7, 5.5, 4, 9],
          'Aprovado': ['sim', 'nao', 'nao', 'sim']}

In [12]:
alunosDF = pd.DataFrame(alunosDIC)
alunosDF

Nome  Nota Aprovado
0     Joao   7.0      sim
1    Maria   5.5      nao
2  Eduardo   4.0      nao
3   Felipe   9.0      sim

In [13]:
serie1 = pd.Series([9, 10, 7, 15, 17])
serie1

0     9
1    10
2     7
3    15
4    17
dtype: int64

In [14]:
import numpy as np 

array1 = np.array([6, 5, 2, 32, 78])
array2 = np.array([(44, 56, 3, 7, 8), (34, 786, 67, 45, 67)])

print(array1)
print(array2)

[ 6  5  2 32 78]
[[ 44  56   3   7   8]
 [ 34 786  67  45  67]]


In [15]:
serie2 = pd.Series(array1)
serie2

0     6
1     5
2     2
3    32
4    78
dtype: int32

In [14]:
## POO 

In [3]:
class Jogador:
    def __init__(self, nome, fichas):
        self.nome = nome
        self.fichas = fichas
    def passou_fase(self):
        self.fichas = self.fichas + 10
    
    def __str__(self):
        return f"{self.nome}: {self.fichas}"
    
    def __repr__(self):
        return str(self)


In [7]:
guilherme = Jogador("Guilherme", 100)
print(guilherme)
guilherme.passou_fase()
print(guilherme)

daniel = Jogador("Daniel", 200)
print(daniel)
daniel.passou_fase()
print(daniel)

daniel.fichas = 225
print(daniel)



Guilherme: 100
Guilherme: 110
Daniel: 200
Daniel: 210
Daniel: 225


In [ ]:
## ATRIBUTOS E METODOS ESTATICOS

In [11]:
class Jogador:
    NUMERO_DE_JOGADORES = 0
    def __init__(self, nome, fichas):
        self.nome = nome
        self.fichas = fichas
        Jogador.NUMERO_DE_JOGADORES += 1
    def passou_fase(self):
        self.fichas = self.fichas + 10
    
    def __str__(self):
        return f"{self.nome}: {self.fichas}"
    
    def __repr__(self):
        return str(self)

In [12]:
guilherme = Jogador("Guilherme", 100)
print(guilherme)
guilherme.passou_fase()
print(guilherme)

daniel = Jogador("Daniel", 200)
print(daniel)
daniel.passou_fase()
print(daniel)

daniel.fichas = 225
print(daniel)



Guilherme: 100
Guilherme: 110
Daniel: 200
Daniel: 210
Daniel: 225


In [13]:
print(Jogador.NUMERO_DE_JOGADORES)

2


In [21]:
from typing import List
class Jogador:
    NUMERO_DE_JOGADORES = 0
    def __init__(self, nome, fichas):
        self.nome = nome
        self.fichas = fichas
        Jogador.NUMERO_DE_JOGADORES += 1
   
    def passou_fase(self):
        self.fichas = self.fichas + 10
    
    @staticmethod
    def ganhador(arr_jogadores: List["Jogador"]):
        jogador_aux = arr_jogadores[0]
        for jogador in arr_jogadores:
            if jogador.fichas > jogador_aux.fichas:
                jogador_aux = jogador
        return jogador_aux
    
    def __str__(self):
        return f"{self.nome}: {self.fichas}"
    
    def __repr__(self):
        return str(self)

In [23]:
guilherme = Jogador("Guilherme", 100)
guilherme.passou_fase()

daniel = Jogador("Daniel", 200)
daniel.passou_fase()
daniel.fichas = 225
guilherme.fichas = 335

jogadores = [guilherme, daniel]
jogador_vencedor = Jogador.ganhador(jogadores)

print(f"Vencedor: {jogador_vencedor}")



Vencedor: Guilherme: 335


In [27]:
class Pessoa:
    def __init__(self, nome):
        self.nome = nome
    
    def diz_oi(self, pessoa: "Pessoa"):
        print(f"{self.nome} diz oi para {pessoa.nome}!")


In [28]:
joao = Pessoa("João")
maria = Pessoa("Maria")

maria.diz_oi(joao)

Maria diz oi para João!


In [31]:
class Funcionario(Pessoa):
    def __init__(self, nome, salario):
        super().__init__(nome)
        self.salario = salario
    def aumento_salario(self, aumento):
        self.salario += aumento

In [33]:
matias = Funcionario("matias", 1000)
print(matias.salario)
matias.aumento_salario(100)
print(matias.salario)

matias.diz_oi(maria)

1000
1100
matias diz oi para Maria!


In [35]:
class Funcionario(Pessoa):
    def __init__(self, nome, salario):
        super().__init__(nome)
        self.salario = salario
    def aumento_salario(self, aumento):
        self.salario += aumento
    def diz_oi(self, pessoa: "Pessoa"):
        print(f"{self.nome} diz: Bom dia {pessoa.nome}, como vai?")


In [36]:
matias = Funcionario("matias", 1000)
print(matias.salario)
matias.aumento_salario(100)
print(matias.salario)

matias.diz_oi(maria)

1000
1100
matias diz: Bom dia Maria, como vai?


In [ ]:
METODOS ABSTRATOS

In [50]:
from datetime import datetime
from abc import abstractmethod

class Conta:
    def __init__(self, numero, saldo):
        self.numero = numero 
        self.saldo = saldo

class TransacaoBancaria:
    def __init__(self, conta: Conta, data: datetime, valor: float):
        self.conta = conta
        self.data = data
        self.valor = valor
   
    @abstractmethod
    def efetua_transacao(self):
        raise NotImplementedError

In [54]:
class TransacaoCredito(TransacaoBancaria):
    def efetua_transacao(self):
        self.conta.saldo += self.valor

class TransacaoDebito(TransacaoBancaria):
    def efetua_transacao(self):
        self.conta.saldo -= self.valor

In [56]:
conta = Conta(111, 2000)
print(f"Saldo Inicial: {conta.saldo}")

cred_30 = TransacaoCredito(conta, datetime.now(), 30)
cred_40 = TransacaoCredito(conta, datetime.now(), 40)
deb_300 = TransacaoDebito(conta, datetime.now(), 300)

arr_transacoes = [cred_30, cred_40, deb_300]

for transacao in arr_transacoes:
    transacao.efetua_transacao()

print(f"Saldo Final: {conta.saldo}")

Saldo Inicial: 2000
Saldo Final: 1770
