In [11]:
import pandas as pd

alunosDIC = {'Nome': ['Joao', 'Maria', 'Eduardo', 'Felipe'],
          'Nota': [7, 5.5, 4, 9],
          'Aprovado': ['sim', 'nao', 'nao', 'sim']}

In [12]:
alunosDF = pd.DataFrame(alunosDIC)
alunosDF

Nome  Nota Aprovado
0     Joao   7.0      sim
1    Maria   5.5      nao
2  Eduardo   4.0      nao
3   Felipe   9.0      sim

In [13]:
serie1 = pd.Series([9, 10, 7, 15, 17])
serie1

0     9
1    10
2     7
3    15
4    17
dtype: int64

In [14]:
import numpy as np 

array1 = np.array([6, 5, 2, 32, 78])
array2 = np.array([(44, 56, 3, 7, 8), (34, 786, 67, 45, 67)])

print(array1)
print(array2)

[ 6  5  2 32 78]
[[ 44  56   3   7   8]
 [ 34 786  67  45  67]]


In [15]:
serie2 = pd.Series(array1)
serie2

0     6
1     5
2     2
3    32
4    78
dtype: int32